[Variables]

Location=SPXX0050
Unit=m
ScrollMouseIncrement=0.05
Format=#I
Hidden=1
Hidden2=0
Player=Winamp
Color1=0,0,0
Color2=255,255,255
UserName=Connect-R

;I will try to explain to you as much as i can.This "#@#\" is shortened for "@Resources" folder.It's a folder where the icons and other parts of the skin are located.
;If you want to change icon-s,new icon-s,you must put in "@Resources" folder.Also,icons must be in PNG file format.
;When you change "icon and name path",for example if you want to change "My Computer" icon to "CCleaner",it should look like this:

;This is example for some program:

;Icon1NameAndPath=#@#\CCleaner.png
;Icon1Text=CCleaner
;LocationPath1=["C:\Program Files\CCleaner\CCleaner64.exe"]

;This is example for some internet links:

;Icon4NameAndPath=#@#\Twitter.png
;Icon4Text=Twitter
;LocationPath4=["https://twitter.com/?lang=en"]

;etc..

;----------------------Dock Settings--------------------------
;-------------------------------------------------------------


Icon1NameAndPath=#@#\My Computer.png
Icon1Text=My Computer
LocationPath1=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

Icon2NameAndPath=#@#\My Documents.png
Icon2Text=My Documents
LocationPath2=[Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]

Icon3NameAndPath=#@#\Videos.png
Icon3Text=Video
LocationPath3=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]

Icon4NameAndPath=#@#\Pictures.png
Icon4Text=Pictures
LocationPath4=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]

Icon5NameAndPath=#@#\Music.png
Icon5Text=Music
LocationPath5=[Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]

Icon6NameAndPath=#@#\Downloads.png
Icon6Text=Downloads
LocationPath6=[Shell:::{374DE290-123F-4565-9164-39C4925E467B}]

Icon7NameAndPath=#@#\Google.png
Icon7Text=Google
LocationPath7=["https://google.com"]

Icon8NameAndPath=#@#\Facebook.png
Icon8Text=Facebook
LocationPath8=["https://facebook.com/"]

Icon9NameAndPath=#@#\Gmail.png
Icon9Text=Gmail
LocationPath9=["https://mail.google.com/mail/"]

Icon10NameAndPath=#@#\Deviantart.png
Icon10Text=Deviantart
LocationPath10=["https://www.deviantart.com/browse/all/customization/skins/sysmonitor/rainmeter/?order=5"]

Icon11NameAndPath=#@#\YouTube.png
Icon11Text=YouTube
LocationPath11=["https://www.youtube.com/"]

Icon12NameAndPath=#@#\Soundcloud.png
Icon12Text=Sound Cloud
LocationPath12=["https://soundcloud.com/"]

Icon13NameAndPath=#@#\Tweeter.png
Icon13Text=Tweeter
LocationPath13=["https://twitter.com/"]

Icon14NameAndPath=#@#\Instagram.png
Icon14Text=Instagram
LocationPath14=["https://www.instagram.com"]

Icon15NameAndPath=#@#\Pinterest.png
Icon15Text=Pinterest
LocationPath15=["https://www.pinterest.com/"]

Icon16NameAndPath=#@#\Reddit.png
Icon16Text=Reddit
LocationPath16=["https://www.reddit.com/"]





